// <auto-generated />
using System;
using AgilerapProcessSystems.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgilerapProcessSystems.Migrations
{
    [DbContext(typeof(Agile_Process_SystemsContext))]
    partial class Agile_Process_SystemsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgilerapProcessSystems.Models.Provider", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CreateByID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdateByID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<int?>("WorkID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CreateByID");

                    b.HasIndex("UpdateByID");

                    b.HasIndex("UserID");

                    b.HasIndex("WorkID");

                    b.ToTable("Provider");
                });

            modelBuilder.Entity("AgilerapProcessSystems.Models.ProviderLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CreateByID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdateByID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<int?>("WorkLogID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CreateByID");

                    b.HasIndex("UpdateByID");

                    b.HasIndex("UserID");

                    b.HasIndex("WorkLogID");

                    b.ToTable("ProviderLog");
                });

            modelBuilder.Entity("AgilerapProcessSystems.Models.Status", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("StatusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("AgilerapProcessSystems.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LineID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("AgilerapProcessSystems.Models.Work", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CreateByID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HeaderID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusID")
                        .HasColumnType("int");

                    b.Property<int?>("UpdateByID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CreateByID");

                    b.HasIndex("StatusID");

                    b.HasIndex("UpdateByID");

                    b.ToTable("Work");
                });

            modelBuilder.Entity("AgilerapProcessSystems.Models.WorkLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CreateByID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("No")
                        .HasColumnType("int");

                    b.Property<string>("Project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusID")
                        .HasColumnType("int");

                    b.Property<int?>("UpdateByID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WorkID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CreateByID");

                    b.HasIndex("StatusID");

                    b.HasIndex("UpdateByID");

                    b.HasIndex("WorkID");

                    b.ToTable("WorkLog");
                });

            modelBuilder.Entity("AgilerapProcessSystems.Models.Provider", b =>
                {
                    b.HasOne("AgilerapProcessSystems.Models.User", "CreateBy")
                        .WithMany()
                        .HasForeignKey("CreateByID");

                    b.HasOne("AgilerapProcessSystems.Models.User", "UpdateBy")
                        .WithMany()
                        .HasForeignKey("UpdateByID");

                    b.HasOne("AgilerapProcessSystems.Models.User", "User")
                        .WithMany("Provider")
                        .HasForeignKey("UserID");

                    b.HasOne("AgilerapProcessSystems.Models.Work", "Work")
                        .WithMany("Provider")
                        .HasForeignKey("WorkID");

                    b.Navigation("CreateBy");

                    b.Navigation("UpdateBy");

                    b.Navigation("User");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("AgilerapProcessSystems.Models.ProviderLog", b =>
                {
                    b.HasOne("AgilerapProcessSystems.Models.User", "CreateBy")
                        .WithMany()
                        .HasForeignKey("CreateByID");

                    b.HasOne("AgilerapProcessSystems.Models.User", "UpdateBy")
                        .WithMany()
                        .HasForeignKey("UpdateByID");

                    b.HasOne("AgilerapProcessSystems.Models.User", "User")
                        .WithMany("ProviderLog")
                        .HasForeignKey("UserID");

                    b.HasOne("AgilerapProcessSystems.Models.WorkLog", "WorkLog")
                        .WithMany("ProviderLog")
                        .HasForeignKey("WorkLogID");

                    b.Navigation("CreateBy");

                    b.Navigation("UpdateBy");

                    b.Navigation("User");

                    b.Navigation("WorkLog");
                });

            modelBuilder.Entity("AgilerapProcessSystems.Models.Work", b =>
                {
                    b.HasOne("AgilerapProcessSystems.Models.User", "CreateBy")
                        .WithMany()
                        .HasForeignKey("CreateByID");

                    b.HasOne("AgilerapProcessSystems.Models.Status", "Status")
                        .WithMany("Work")
                        .HasForeignKey("StatusID");

                    b.HasOne("AgilerapProcessSystems.Models.User", "UpdateBy")
                        .WithMany()
                        .HasForeignKey("UpdateByID");

                    b.Navigation("CreateBy");

                    b.Navigation("Status");

                    b.Navigation("UpdateBy");
                });

            modelBuilder.Entity("AgilerapProcessSystems.Models.WorkLog", b =>
                {
                    b.HasOne("AgilerapProcessSystems.Models.User", "CreateBy")
                        .WithMany()
                        .HasForeignKey("CreateByID");

                    b.HasOne("AgilerapProcessSystems.Models.Status", "Status")
                        .WithMany("WorkLog")
                        .HasForeignKey("StatusID");

                    b.HasOne("AgilerapProcessSystems.Models.User", "UpdateBy")
                        .WithMany()
                        .HasForeignKey("UpdateByID");

                    b.HasOne("AgilerapProcessSystems.Models.Work", "Work")
                        .WithMany("WorkLog")
                        .HasForeignKey("WorkID");

                    b.Navigation("CreateBy");

                    b.Navigation("Status");

                    b.Navigation("UpdateBy");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("AgilerapProcessSystems.Models.Status", b =>
                {
                    b.Navigation("Work");

                    b.Navigation("WorkLog");
                });

            modelBuilder.Entity("AgilerapProcessSystems.Models.User", b =>
                {
                    b.Navigation("Provider");

                    b.Navigation("ProviderLog");
                });

            modelBuilder.Entity("AgilerapProcessSystems.Models.Work", b =>
                {
                    b.Navigation("Provider");

                    b.Navigation("WorkLog");
                });

            modelBuilder.Entity("AgilerapProcessSystems.Models.WorkLog", b =>
                {
                    b.Navigation("ProviderLog");
                });
#pragma warning restore 612, 618
        }
    }
}
